---
title: "Models as games: a novel approach for 'gamesourcing' parameter data and communicating complex models"
output:
  word_document:
    reference_docx: "template.docx"
  html_document:
    css: main_ms.css
bibliography: references.bib
link-citations: true
number-sections: true
---

```{r setup, include=FALSE}
library(GMSE)
library(shiny)
library(shinyBS)
library(shinyjs)
library(waiter)
knitr::opts_chunk$set(echo = TRUE)
```

# Summary

# Introduction

In recent years, the use and application of models has become widespread and indispensable in conservation science, ranging from demonstrating the likely effects of climate change [@ipcc2021] to supporting the understanding of fundamental processes in natural resource management [e.g. @fryxell2010; @cusack2020].
Given the continued rapid global loss of biodiversity [@ceballos2015; @ceballos2017], understanding the mechanisms and consequences of such loss is vital.
Although a number of drivers of biodiversity loss have been identified [e.g. @maxwell2016a], one of the most prevalent and widespread ones is human exploitation of habitats and natural resources, both directly (e.g. through hunting or habitat loss to agriculture) or indirectly (e.g. through international trade in natural resources) [e.g. @wilting2017].
Because resource use is fundamentally driven by economic and social processes, it has long been recognised that accurate predictions thereof is reliant as much on understanding resource dynamics as it is on understanding human behaviour and decision-making [@milner-gulland2012; @schlüter2012].
Thus, the development of socio-ecological models in which natural resource dynamics and human decision making interact is becoming increasingly urgent.

Cutting-edge modelling approaches have made significant progress towards this goal.
For example, @orach2020 used an agent-based model to show how coalitions of interest groups can stabilise natural resource dynamics, whereas @cusack2020 used a novel agent-based modelling framework [@duthie2018] to assess the effect of lobbying on species extinction risk.
Although such modelling efforts represent significant progress in modelling complex socio-ecological systems, their increased complexity poses to two, interlinked, challenges.
First, models are often difficult to communicate clearly to non-specialist audiences in the first place, and this challenge increases with model complexity [@grimm2006].
This is particularly important for models for resource use in socio-ecological systems, as they are often specifically intended for use by managers or stakeholders who may lack technical expertise.
Much has been said about improving the uptake of models in such settings [e.g. @addison2013; @schuwirth2019; @will2021], and detailed documentation of the purpose, organisation and predictions has been highlighted as particularly important [@grimm2020].
Even so, often the evidence for practical uptake of many models is limited [@addison2013; @zasada2017].
Second, their complexity implies the need for extensive data to parameterise them effectively.
In terms of socio-ecological systems, while data to parameterise the ecological component are often relatively easily available, the human decision-making components are often based on limited theory and lack a general empirical basis [@groeneveld2017].
Not only may this lead to limited predictive power, a perceived lack of empirical basis may negatively affect their acceptance by stakeholders [cf. model "quality" as in @kolkman2016].
To maximise the adoption of complex socio-ecological models as management tools, both appropriate representation of human decision-making and effective communication are therefore key.

Games have a long history of being in research [@sandbrook2015; @chabris2017; @redpath2018], including as tools to aid the communication of complex ideas and processes to non-specialists [@garcia2016; @tan2018; @fjaellingsdal2019].
Given this long history, it is striking that the parallels between games (particularly videogames) and models are not discussed more widely.
All models are abstract representations of environments, actors and relationships, with inputs (parameters) and outputs (predictions or inferences).
Similarly, all games present a player with an environment in a given state (parameters), including one or more actors, which can take actions (inputs) to affect the environment for a given effect (outputs).
It is worth stressing that every game has an underlying model that defines the state of the environment, relationships between objects in this environment, and inputs and outputs available to the player.
However, while games are by definition designed with player (user) interaction in mind, models rarely have user-facing or even user-friendly interfaces, and running or adapting them to specific circumstances usually relies on technical expertise.
Casting models as games provides an opportunity to effectively improve the communication and understandability of even relatively complex models.
Inputs and outputs may be presented in a visual way and tweaked depending on the type of audience, and both potential applications and limitations of the model can be demonstrated effectively.

In addition, presenting a model as a game provides an opportunity to empirically collect data on how stakeholders make decisions in the modelled environment.
Games have already been widely used for data collection to answer specific questions [e.g. @meinzen-dick2016; @villamor2016; @rakotonarivo2021; @rakotonarivo2021a] on what affects decision-making in socio-ecological systems.
A less well-explored potential of using this approach is using in-game decisions directly as a "big data" source to improve the parameterisation of the underlying model itself.
Many existing models represent human decision-making by relatively crude algorithms (e.g. fully rational utility maximisation) despite widespread recognition that this does not reflect real-world decision-making [@groeneveld2017].
By presenting real-world stakeholders with in-game decisions that would otherwise be taken by a predefined algorithm, large data sets of actions and outcomes may be collected.
Given a large enough sample of players and in-game conditions, such data might then be used to train decision-making algorithms that better reflect human decision-making in natural resource management[^1].
It is notable that this "gamesourcing" or "Gamorithm" [@sipper2020] approach has already been widely used in a number of other fields (e.g. crowdsourcing accurate protein-structure models [@khatib2011], and classification of fluorescence microscopy images [@sullivan2018]), but remains rare in conservation science [but see @vandenbergh2021].
Thus, model-games can be considered "virtual laboratories" [@duthie2021] to not only test specific hypotheses or predictions, but potentially also as an effective method to source data to parameterise the underlying models, based on in-game decisions by real humans.

We here aim to illustrate the potential for this model-game approach, both in terms of aiding model communication as well data collection for improved parameterisation, by introducing Animal&Farm (A&F).
We developed A&F as a simple interactive game front-end for a complex socio-ecological modelling framework (GMSE), in which the player acts as the manager of a virtual environment in which a population of wild grazing animals (the natural resource) may adversely affect farming yield, with farmers acting to maximise their yield and potentially hunting the animals.
We argue that that by acting as an interface between users (i.e. players) and a complex underlying model with many components and assumptions, such a game can simultaneously (1) aid the communication and useability of the underlying model and (2) can be used to gather data to improve the parameterisation of such models.
We first briefly summarise the underlying modelling framework, its potential and limitations.
Second, we describe both the structure of A&F itself as well as its database back-end.
Third, we outline how this approach may be used to collect data on player decision-making in simulated *in silico* experiments, and present some example results of doing so; noting that these findings are intended as illustrative only.
Finally, using test player feedback as a basis, we discuss both the limitations of this approach as well as its wider potential.

# Outline of approach

[A&F is available to play online](https://ochil-ds.co.uk/animalnfarm/).

Overall, it consists of two main components; (1) the underlying model(s) describing the wild grazing animal ("resource") population dynamics, the observation of this population, and farmer ("user" or stakeholder) actions, all implemented using the GMSE framework as described below; and (2) the game interface for the underlying model, which allows the player to set management actions (specifically, costs for user actions) that would otherwise be determined by the management model in the "vanilla" GMSE set up.

## Underlying model: GMSE

### Basic introduction of GMSE principles and structures

### Brief discussion of limitations of GMSE

## Animal&Farm

### Structure as relating to GMSE

In the default implementation of GMSE `r packageVersion("GMSE")`, a single time $t$ step consists of a series of calls to the resource model, observation model, management model and user model, in that specific order; in other words, a time step ends after user actions have been chosen (by the GA) and implemented [**FIG Xa**].
To allow players to assess the environment and interactively choose management actions, A&F uses a modified version of GMSE.

A&F uses a development version of GMSE (v. `r packageVersion("GMSE")`, implemented in `r sessionInfo()$R.version$version.string`, code available [here](https://github.com/ConFooBio/gmse/tree/man_control) in which the management model is replaced by user (player) inputs, and the order of operations is altered to accommodate this.
To initialise each game session, four time steps are run using the default GMSE implementation; i.e. in these time steps the management decisions are chosen by the default GA, and the resource, observation and user models are run using the parameters as defined for the given the scenario (**see below**).
These time steps are followed by a "partial" time step where only the resource and observation models are run, skipping the management and user models.
As a result, at the end of these initial time steps ([`init_man_control()`](%5B%60https://github.com/ConFooBio/gmse/blob/0e8aab2fb325421915a7c3615820812e45f42a74/R/gmse_apply_control.R#L368%60%5D(https://github.com/ConFooBio/gmse/blob/0e8aab2fb325421915a7c3615820812e45f42a74/R/gmse_apply_control.R#L368))), the simulated system has five population and observation time steps and is ready for the next choice of management action at $t = 5$, pending the first player input.
This is done both to set up all the required GMSE data structures using existing code, as well as to provide the player with a short time series on which to base management decisions going forward.

The current GMSE simulations used by A&F simulates a landscape of 100x100 cells, divided into farms owned by 4-12 farmers (stakeholders; the precise number and land distribution is randomly varied per session, see **section XXX** below. ).
Farmers can take three possible actions; tending crops, hunting (culling) animals, or scaring animals off their land.
All submodels used in A&F are currently the default GMSE models (with the exception of the management model in time steps $t>5$, where the player assumes control over the management decisions (see below).
Thus, we only give brief details here, for full details and descriptions of all models, see **XXX** and **XXX**.
The **animal population** model uses the logistic growth form with $N_o = 1000$, $\lambda = 0.3$ and $K=5000$, meaning that in the absence of any management the population is likely to increase from the initial population size (1000) to carrying capacity (5000).
To ensure a level of unpredictability in game play, a random death probability ($0.05 \leq r_d \leq 0.2$) per individual animal per time step is implemented.
The **observation model** uses the default GMSE model (density-based sampling of a subset of the environment); only *observed* numbers of animals are available to the manager to base decisions on (and thus population trajectory plots in the game interface reflect observations only, which are subject to an unknown level of uncertainty).
Both the **management model** (in the initialisation steps) and **user model** use the GA algorithms with default parameter settings.
User (farmer) budgets are set to 1500 units per time step, manager budgets to 1000 units (both for the initial 5 time steps and the subsequent game play).
The users (farmers) aim to maximise yield from their land, their annual budget is reset each year and is unaffected by yield.
Yield is positively affected by tending crops, and may be negatively affected by the presence of grazing wild animals - thus hunting or scaring may offset any potentially negative effects on yield.

Each following A&F time step then consists of (1) user input, taking the place of the default management model, in which the player can assess the environment using outputs provided (see below) and choose management actions (costs for user actions), and, (2) and once the player confirms their choice, a modified GMSE time step including sequential calls to the default user, resource and observation models ([`gmse_apply_UROM()`](https://github.com/ConFooBio/gmse/blob/0e8aab2fb325421915a7c3615820812e45f42a74/R/gmse_apply_control.R#L146)) [**FIG Xb**].

### User interface

The user interface for A&F is a web application is coded in R, using [`Shiny`](https://CRAN.R-project.org/package=shiny) (`r packageVersion("shiny")`), and packages [`shinyjs`](https://CRAN.R-project.org/package=shinyjs) (`r packageVersion("shinyjs")`), [`shinyBS`](https://CRAN.R-project.org/package=shinyBS) (`r packageVersion("shinyBS")`), and [`waiter`](https://CRAN.R-project.org/package=waiter) (`r packageVersion("waiter")`).

On starting a new game session, the player is presented with a series of introductory screens explaining the background, flow and objective of the game <!--# Maybe add a note on generic idea to maximise score? -->, after which they are asked to enter a player name, which is stored and used to show player scores as the end of a session, compared to previous sessions by other players.

The main game screen consists of four components (**FIG X**).
First, a trajectory plot (**Fig Xa**) showing (1) observed animal population numbers and (2) agricultural yield for each farmer in each time step, up to time $t$ (at the start of the game this will show five observations from the initialisation steps described above).
Agricultural yield is expressed as a % of "maximum unaffected yield", i.e. yield in the absence of damage from wildlife or investment in tending crops.
Second, a plot of the landscape (**Fig Xb**) showing the distribution of farm ownership as well as the position of animals at time $t$.
Third, a bar plot of the number of actions taken by each farmer at time $t$ (**Fig Xc**).
Fourth, a report of the current management budget available (not allocated), player scores (**see below**), and player inputs (**Fig Xd**).
The player (manager) inputs consist of two sliders, setting the cost for two out of the three actions available[^2] to farmers in time $t+1$: killing animals (presented as the cost of a hunting licence) and scaring animals off their land (presented as the cost of a scaring licence).
Management budget allocated to one of these cannot be allocated to another, and any budget not allocated is not rolled over to the next time step.
The third action available to farmers (tending crops) cannot be directly[^3] affected by the manager (player), so no input is available for this
.

The game progresses to the next time step $t+1$ once the player confirms their choice of cost inputs.
At this point (1) the user, resource and observation models are run using the updated action costs set by the player, (2) selected environment state data are stored in the database (**see below**), and (3) trajectory, landscape and action plots are updated and budget allocation is reset.
The current implementation of A&F continues for a maximum of 20 time steps (following the initial five) at which point the game session is ended and the player is presented with a scoreboard.
If the resource population reaches extinction, the game session is also terminated.

### Game objective, scores and scoreboard

Other than preventing extinction of the animal population, A&F does not have a particular game objective; instead, the player is asked to make management decisions reflecting their preference of animal population and agricultural yield trajectory.
<!--# Insert some notes on how this is done to ensure decision making isn't biased fully towards conservation or agriculture, how this is different to management algorithm goal in GMSE? -->The player is, however, presented with two scores which allows them to assess their performance relative to their own previous game sessions as well as those of other players.

The scores are arbitrarily defined to reflect performance in terms of the animal population ("animal score", $A_t$) on the one hand, and overall agricultural yield ("yield score", $Y_t$) on the other.
Both scores can be interpreted as the mean % of the initial (i.e. at time $t=5$) true size of the animal population $N_t$ and landscape yield $y_t$, with $y_t$ calculated as the mean yield over all landscape cells at time $t$ <!--# probably need to include a reference to cells/cell values on landscape here -->.

$A_{t} = \frac{\sum_{t=5}^T{\frac{N_t}{N_{t=5}}}}{t}$ and $S_{t}=\frac{\sum_{t=5}^T{y_t}}{t}$ where $t\geq5$ and $T$ the total number of time steps for the game session.
Both scores are intitialised as $A_t = S_t = 100$ when the game is first initialised, to ensure score development over a session can be interpreted as a change from that baseline.

Players can choose to either balance both scores, or score highly on one or the other.
They are updated and displayed on each time step, and the final scores are displayed on a score board after the final time step ($t=25$, so after 20 time steps played) is complete, or once the animal population goes extinct.
The scoreboard is a top 10 "leaderboard" of scores over all sessions played by all players to date; if the current player's score is not included in the top 10, it is displayed at the bottom of the board with the correct rank relative to other players.
<!--# Need to include a note on the arbitrary nature of the scores, and how we intend to use them. Either here or in discussion? -->

### Data collection & database

Game play data (e.g. session variables, player inputs, environment state variables) are stored in a MySQL relational database.
Database structure is summarised in Fig X and a full list of parameter values stored and their description is listed in Table X. The current version of A&F stores only a subset of GMSE parameters; this may be easily extended in the future by adding additional fields to the relevant database table and ensuring the database interface functions append extra parameters.
Where values are not stored currently, the default GMSE parameter values are used.

In summary, three main tables are used to store data.

### "Sandbox" for *in silico* experiments

Expandability of parameter variation

Setting up "scenarios" to test specific hypotheses/predictions

# Example application

## Note on ethics approval

## Methods/rationale for scenario set up

## Illustrative results

## Summary of player feedback

### 

# Discussion

## Brief summary of aims, process and outcome of example scenarios

## Revisit player feedback

## Discussion of limitations of overall approach, with reference to player feedback

## (Potentially general discussion of issues with games approach?)

## Discussion of potential

### Communication/education: highlight player feedback as very point of approach: game may be abstract, restrictive and not representative of reality, but this is case for any model, yet latter point often "hidden". By taking game approach, shortcomings more obvious to non-specialists.

### Yes, problematic when expecting direct application to real life, but again this is/should be clear for all models.

### Highlight expandability of approach, sandboxing ideas in flexible simulated environment

## 

# References

[^1]: Note that there are of course limitations to this, and that data on decisions made would only be relevant to the context of the game (i.e. internally valid in the game context).
    Wider external validity depends on a number of factors; we discuss limitations in more detail below.

[^2]: A&F currently focuses only on hunting animals, scaring animals or tending crops as available actions to farmers; this may be expanded in the future to other actions available in GMSE.

[^3]: It can be affected *indirectly* by setting the cost for the two actions prohibitively high, so that tending crops becomes more likely to be most beneficial to maximising yield (the farmer's goal).
    See **XXX**.
